version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://todo_user:todo_password@postgres:5432/todo_db
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: